/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./../../Components/Global/AppButton.vue')['default']
    AppCheckboxInput: typeof import('./../../Components/Global/Forms/Inputs/AppCheckboxInput.vue')['default']
    AppLogo: typeof import('./../../Components/Global/AppLogo.vue')['default']
    AppTextInput: typeof import('./../../Components/Global/Forms/Inputs/AppTextInput.vue')['default']
    Head: typeof import('@inertiajs/vue3')['Head']
    Link: typeof import('@inertiajs/vue3')['Link']
  }
}
