name: Develop

on:
  push:
    branches-ignore:
      - "main"
  pull_request:
    branches: [develop]

jobs:
  tests:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.3

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Prepare Laravel Application
        run: |
          cp .env.ci.example .env
          php artisan key:generate
          php artisan migrate:refresh --force

      - name: Add Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Build Frontend
        run: |
          npm install && npm run build-no-checks

      - name: Run API Tests
        run: vendor/bin/pest --configuration=phpunit.ci.xml --testdox -d memory_limit=512mb --stop-on-failure
